# Generated by Django 4.2.7 on 2023-11-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Complétée'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'Haute'), ('M', 'Moyenne'), ('L', 'Faible')], default='M', max_length=1, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
    ]
